import type { NextPage } from "next";
import Head from "next/head";
import Button from "components/Button";
import { useRecoilState } from "recoil";
import { pageNameState } from "states";
import Link from "next/link";
import { useObserver } from "mobx-react";
import { PageProps, useStore } from "stores";

const Home: NextPage = () => {
  const [pageName, setPageName] = useRecoilState(pageNameState);
  const { name, changeName }: PageProps = useStore().page;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <span>pageName: {pageName} {name}</span>
        <Button pageName={"index"} setPageName={setPageName} changeName={changeName}/>
        <Link href="/post">
          <button>Post Pages 이동</button>
        </Link>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
